#include "jcengine.h"

#include "esp_check.h"

static const char *TAG = "jcengine_story";

enum {
    SPOT_A, SPOT_B, SPOT_C, SPOT_D, SPOT_E, SPOT_F,
    HDG_S = 0, HDG_SW, HDG_W, HDG_NW, HDG_N, HDG_NE, HDG_E, HDG_SE,
};

#define SCENE(name, tag, ss, hs, se, he, day_no, scene_flags) \
    {name, tag, ss, hs, se, he, day_no, scene_flags}

/* Exact table order and metadata from the desktop story_data.go reference. */
static const jcengine_story_scene_t STORY_SCENES[] = {
    SCENE("ACTIVITY.ADS", 1, SPOT_E, HDG_SE, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK),
    SCENE("ACTIVITY.ADS", 12, SPOT_D, HDG_SW, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("ACTIVITY.ADS", 11, 0, 0, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_FIRST | JCENGINE_STORY_VARPOS_OK),
    SCENE("ACTIVITY.ADS", 10, SPOT_D, HDG_SW, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("ACTIVITY.ADS", 4, SPOT_E, HDG_SE, SPOT_E, HDG_SE, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("ACTIVITY.ADS", 5, SPOT_E, HDG_SW, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("ACTIVITY.ADS", 6, SPOT_D, HDG_SW, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK),
    SCENE("ACTIVITY.ADS", 7, SPOT_D, HDG_SW, SPOT_F, HDG_SW, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("ACTIVITY.ADS", 8, 0, 0, SPOT_D, HDG_SE, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FIRST | JCENGINE_STORY_VARPOS_OK),
    SCENE("ACTIVITY.ADS", 9, SPOT_E, HDG_E, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("BUILDING.ADS", 1, SPOT_F, HDG_W, SPOT_A, HDG_W, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("BUILDING.ADS", 4, SPOT_A, HDG_E, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK),
    SCENE("BUILDING.ADS", 3, SPOT_A, HDG_E, SPOT_C, HDG_SE, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("BUILDING.ADS", 2, SPOT_F, HDG_W, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK),
    SCENE("BUILDING.ADS", 5, SPOT_D, HDG_W, SPOT_D, HDG_E, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("BUILDING.ADS", 7, SPOT_D, HDG_W, SPOT_D, HDG_E, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("BUILDING.ADS", 6, SPOT_A, HDG_E, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK),
    SCENE("FISHING.ADS", 1, SPOT_D, HDG_W, SPOT_D, HDG_E, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("FISHING.ADS", 2, SPOT_D, HDG_W, SPOT_D, HDG_E, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("FISHING.ADS", 3, SPOT_D, HDG_W, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("FISHING.ADS", 4, SPOT_E, HDG_E, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_LEFT_ISLAND | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("FISHING.ADS", 5, SPOT_E, HDG_E, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK),
    SCENE("FISHING.ADS", 6, SPOT_D, HDG_W, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("FISHING.ADS", 7, SPOT_E, HDG_E, SPOT_E, HDG_W, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_LEFT_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("FISHING.ADS", 8, SPOT_E, HDG_E, SPOT_E, HDG_W, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_LEFT_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("JOHNNY.ADS", 1, 0, 0, 0, 0, 11, JCENGINE_STORY_FINAL | JCENGINE_STORY_FIRST),
    SCENE("JOHNNY.ADS", 2, SPOT_E, HDG_SW, SPOT_F, 0, 2, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK),
    SCENE("JOHNNY.ADS", 3, SPOT_E, HDG_SW, SPOT_F, HDG_NE, 6, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("JOHNNY.ADS", 4, SPOT_E, HDG_SW, SPOT_F, HDG_NE, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK),
    SCENE("JOHNNY.ADS", 5, SPOT_E, HDG_SW, SPOT_F, HDG_NE, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK),
    SCENE("JOHNNY.ADS", 6, 0, 0, 0, 0, 10, JCENGINE_STORY_FINAL | JCENGINE_STORY_FIRST),
    SCENE("MARY.ADS", 1, SPOT_E, HDG_SW, 0, 0, 5, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("MARY.ADS", 3, SPOT_F, HDG_SW, 0, 0, 4, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_FIRST | JCENGINE_STORY_VARPOS_OK),
    SCENE("MARY.ADS", 2, SPOT_E, HDG_E, 0, 0, 1, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK),
    SCENE("MARY.ADS", 4, SPOT_E, HDG_E, 0, 0, 7, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK),
    SCENE("MARY.ADS", 5, SPOT_E, HDG_NW, 0, 0, 8, JCENGINE_STORY_ISLAND | JCENGINE_STORY_LEFT_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_FIRST | JCENGINE_STORY_NORAFT | JCENGINE_STORY_VARPOS_OK),
    SCENE("MISCGAG.ADS", 1, SPOT_D, HDG_W, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("MISCGAG.ADS", 2, SPOT_D, HDG_W, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_VARPOS_OK),
    SCENE("STAND.ADS", 1, SPOT_A, HDG_SW, SPOT_A, HDG_SW, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("STAND.ADS", 2, SPOT_A, HDG_W, SPOT_A, HDG_W, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("STAND.ADS", 3, SPOT_A, HDG_NW, SPOT_A, HDG_NW, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("STAND.ADS", 4, SPOT_B, HDG_SW, SPOT_B, HDG_SW, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("STAND.ADS", 5, SPOT_B, HDG_S, SPOT_B, HDG_S, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("STAND.ADS", 6, SPOT_B, HDG_SE, SPOT_B, HDG_SE, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("STAND.ADS", 7, SPOT_C, HDG_NE, SPOT_C, HDG_NE, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("STAND.ADS", 8, SPOT_C, HDG_E, SPOT_C, HDG_E, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("STAND.ADS", 9, SPOT_D, HDG_NW, SPOT_D, HDG_NW, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("STAND.ADS", 10, SPOT_D, HDG_NE, SPOT_D, HDG_NE, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("STAND.ADS", 11, SPOT_E, HDG_NW, SPOT_E, HDG_NW, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("STAND.ADS", 12, SPOT_F, HDG_S, SPOT_F, HDG_S, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("STAND.ADS", 15, SPOT_A, HDG_S, SPOT_A, HDG_S, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("STAND.ADS", 16, SPOT_C, HDG_S, SPOT_C, HDG_S, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("SUZY.ADS", 1, 0, 0, 0, 0, 3, JCENGINE_STORY_FINAL | JCENGINE_STORY_FIRST),
    SCENE("SUZY.ADS", 2, 0, 0, 0, 0, 9, JCENGINE_STORY_FINAL | JCENGINE_STORY_FIRST),
    SCENE("VISITOR.ADS", 1, SPOT_A, HDG_S, SPOT_A, HDG_S, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("VISITOR.ADS", 3, SPOT_B, HDG_NW, SPOT_D, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_HOLIDAY_NOK),
    SCENE("VISITOR.ADS", 4, SPOT_D, HDG_S, SPOT_D, HDG_W, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("VISITOR.ADS", 6, SPOT_D, HDG_S, SPOT_D, HDG_SW, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("VISITOR.ADS", 7, SPOT_D, HDG_S, SPOT_D, HDG_SW, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
    /* The plane occupies the right side of the authored frame. Keep this
       event's island at the fixed left position; a variable right placement
       also exposes GJVIS5 tag 8's deliberately off-screen entry sprite. */
    SCENE("VISITOR.ADS", 5, SPOT_E, HDG_SW, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_LEFT_ISLAND | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("WALKSTUF.ADS", 1, SPOT_A, HDG_NE, 0, 0, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_FINAL | JCENGINE_STORY_LOWTIDE_OK),
    SCENE("WALKSTUF.ADS", 2, SPOT_E, HDG_E, SPOT_D, HDG_SE, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK),
    SCENE("WALKSTUF.ADS", 3, SPOT_D, HDG_W, SPOT_E, HDG_W, 0, JCENGINE_STORY_ISLAND | JCENGINE_STORY_VARPOS_OK | JCENGINE_STORY_LOWTIDE_OK),
};

_Static_assert(sizeof(STORY_SCENES) / sizeof(STORY_SCENES[0]) ==
                   JCENGINE_STORY_SCENE_COUNT,
               "story scene count changed");

size_t jcengine_story_scene_count(void)
{
    return sizeof(STORY_SCENES) / sizeof(STORY_SCENES[0]);
}

const jcengine_story_scene_t *jcengine_story_scene(size_t index)
{
    return index < jcengine_story_scene_count() ? &STORY_SCENES[index] : NULL;
}

bool jcengine_story_scene_eligible(const jcengine_story_scene_t *scene,
                                   uint8_t wanted_flags,
                                   uint8_t unwanted_flags,
                                   uint8_t current_day)
{
    return scene != NULL && (scene->flags & wanted_flags) == wanted_flags &&
           (scene->flags & unwanted_flags) == 0 &&
           (scene->day == 0 || scene->day == current_day);
}

esp_err_t jcengine_story_pick_in_order(uint8_t wanted_flags,
                                       uint8_t unwanted_flags,
                                       uint8_t current_day, size_t *cursor,
                                       const jcengine_story_scene_t **scene)
{
    ESP_RETURN_ON_FALSE(cursor != NULL && scene != NULL, ESP_ERR_INVALID_ARG,
                        TAG, "invalid story selector");
    size_t count = jcengine_story_scene_count();
    for (size_t step = 0; step < count; ++step) {
        size_t index = (*cursor + step) % count;
        if (jcengine_story_scene_eligible(&STORY_SCENES[index], wanted_flags,
                                          unwanted_flags, current_day)) {
            *cursor = (index + 1) % count;
            *scene = &STORY_SCENES[index];
            return ESP_OK;
        }
    }
    *scene = NULL;
    return ESP_ERR_NOT_FOUND;
}
