/* Generated by tools/gen_scene_names.py. Do not edit. */
#include "jcengine.h"
#include "sdkconfig.h"

#include <string.h>

typedef struct {
    const char *ads_name;
    uint16_t ads_tag;
    const char *title;
} scene_name_record_t;

#if CONFIG_JC_SCENE_NAMES
static const scene_name_record_t SCENE_NAMES[] = {
    {"ACTIVITY.ADS", 1, "DIVING GAGS"},
    {"ACTIVITY.ADS", 12, "SEAGULL SITS READING"},
    {"ACTIVITY.ADS", 11, "SEAGULL STEALS CLOTHES"},
    {"ACTIVITY.ADS", 10, "SEAGULL STEALS BOOK"},
    {"ACTIVITY.ADS", 4, "PALM TREE DIVE"},
    {"ACTIVITY.ADS", 5, "RAIN DANCE"},
    {"ACTIVITY.ADS", 6, "READING GAG"},
    {"ACTIVITY.ADS", 7, "READING A BOOK"},
    {"ACTIVITY.ADS", 8, "OCEAN BATH"},
    {"ACTIVITY.ADS", 9, "NATIVE BOAT VISIT"},
    {"BUILDING.ADS", 1, "BUILD SANDCASTLE"},
    {"BUILDING.ADS", 4, "PIRATES TIE JOHNNY"},
    {"BUILDING.ADS", 3, "SLEEPING"},
    {"BUILDING.ADS", 2, "LILLIPUTIAN BOAT"},
    {"BUILDING.ADS", 5, "BUILD CAMPFIRE"},
    {"BUILDING.ADS", 7, "COOK AND EAT"},
    {"BUILDING.ADS", 6, "NIGHT LILLIPUTIANS"},
    {"FISHING.ADS", 1, "FISHING FOR JUNK"},
    {"FISHING.ADS", 2, "FISHING KEEPERS"},
    {"FISHING.ADS", 3, "LARGE OCTOPUS"},
    {"FISHING.ADS", 4, "FISHING CATCH ONE"},
    {"FISHING.ADS", 5, "SQUIRTING GREEN FISH"},
    {"FISHING.ADS", 6, "FISHING CATCH THREE"},
    {"FISHING.ADS", 7, "SHORE FISHING JUNK"},
    {"FISHING.ADS", 8, "SHORE FISH KEEPERS"},
    {"JOHNNY.ADS", 1, "BACK ON THE ISLAND"},
    {"JOHNNY.ADS", 2, "FIRST MESSAGE"},
    {"JOHNNY.ADS", 3, "FINAL MESSAGE"},
    {"JOHNNY.ADS", 4, "FIND MESSAGE BOTTLE"},
    {"JOHNNY.ADS", 5, "THROW MESSAGE BOTTLE"},
    {"JOHNNY.ADS", 6, "DREAMING AT WORK"},
    {"MARY.ADS", 1, "DINNER WITH MERMAID"},
    {"MARY.ADS", 3, "ASK MERMAID ON DATE"},
    {"MARY.ADS", 2, "FIRST MERMAID GLIMPSE"},
    {"MARY.ADS", 4, "MERMAID BREAKUP"},
    {"MARY.ADS", 5, "LEAVE THE ISLAND"},
    {"MISCGAG.ADS", 1, "MELTING IN THE SUN"},
    {"MISCGAG.ADS", 2, "SHARK ATTACK"},
    {"STAND.ADS", 1, "STAND A SW"},
    {"STAND.ADS", 2, "STAND A W"},
    {"STAND.ADS", 3, "STAND A NW"},
    {"STAND.ADS", 4, "STAND B SW"},
    {"STAND.ADS", 5, "STAND B S"},
    {"STAND.ADS", 6, "STAND B SE"},
    {"STAND.ADS", 7, "STAND C NE"},
    {"STAND.ADS", 8, "STAND C E"},
    {"STAND.ADS", 9, "STAND D NW"},
    {"STAND.ADS", 10, "STAND D NE"},
    {"STAND.ADS", 11, "STAND E NW"},
    {"STAND.ADS", 12, "STAND F NE"},
    {"STAND.ADS", 15, "TELESCOPE A"},
    {"STAND.ADS", 16, "TELESCOPE C"},
    {"SUZY.ADS", 1, "SUZY FINDS MESSAGE"},
    {"SUZY.ADS", 2, "JOHNNY MEETS SUZY"},
    {"VISITOR.ADS", 1, "UNSEEN VISITORS"},
    {"VISITOR.ADS", 3, "TANKER VISIT"},
    {"VISITOR.ADS", 4, "COCONUT FALLS"},
    {"VISITOR.ADS", 6, "COCONUT ROLLS"},
    {"VISITOR.ADS", 7, "CHASE THE COCONUT"},
    {"VISITOR.ADS", 5, "COCONUT HITS PLANE"},
    {"WALKSTUF.ADS", 1, "WOULD-BE RESCUERS"},
    {"WALKSTUF.ADS", 2, "BUILD THE RAFT"},
    {"WALKSTUF.ADS", 3, "JOGGING"},
};

static const jcengine_scene_menu_entry_t SCENE_MENU[] = {
    {"SCENE_01", "Swimming", "Diving gags", "ACTIVITY.ADS#1", ""},
    {"SCENE_02", "Seagull", "Seagull sits while Johnny reads", "ACTIVITY.ADS#12", ""},
    {"SCENE_03", "Seagull", "Seagull steals clothes while bathing", "ACTIVITY.ADS#11", ""},
    {"SCENE_04", "Seagull", "Seagull steals the book", "ACTIVITY.ADS#10", ""},
    {"SCENE_05", "Swimming", "Normal dive from the palm tree", "ACTIVITY.ADS#4", ""},
    {"SCENE_06", "Rare and Unusual", "Rain dance", "ACTIVITY.ADS#5", ""},
    {"SCENE_07", "Reading", "Reading gag", "ACTIVITY.ADS#6", ""},
    {"SCENE_08", "Reading", "Johnny reads a book", "ACTIVITY.ADS#7", ""},
    {"SCENE_09", "Swimming", "Johnny bathes in the sea", "ACTIVITY.ADS#8", ""},
    {"SCENE_10", "Visitors", "Visitors photograph native Johnny", "ACTIVITY.ADS#9", ""},
    {"SCENE_11", "Common", "Johnny builds a sandcastle", "BUILDING.ADS#1", ""},
    {"SCENE_12", "Pirates", "Pirates tie Johnny down", "BUILDING.ADS#4", ""},
    {"SCENE_13", "Common", "Johnny sleeps", "BUILDING.ADS#3", ""},
    {"SCENE_14", "Pirates", "Lilliputians arrive by boat", "BUILDING.ADS#2", ""},
    {"SCENE_15", "Common", "Johnny builds a campfire", "BUILDING.ADS#5", ""},
    {"SCENE_16", "Common", "Johnny cooks and eats", "BUILDING.ADS#7", ""},
    {"SCENE_17", "Pirates", "Lilliputians at night", "BUILDING.ADS#6", ""},
    {"SCENE_18", "Fishing", "Johnny fishes for junk", "FISHING.ADS#1", ""},
    {"SCENE_19", "Fishing", "Johnny fishes for keepers", "FISHING.ADS#2", ""},
    {"SCENE_20", "Fishing", "Johnny catches a large octopus", "FISHING.ADS#3", ""},
    {"SCENE_21", "Fishing", "Fishing catch variation one", "FISHING.ADS#4", ""},
    {"SCENE_22", "Fishing", "Green fish squirts Johnny", "FISHING.ADS#5", ""},
    {"SCENE_23", "Fishing", "Fishing catch variation three", "FISHING.ADS#6", ""},
    {"SCENE_24", "Fishing", "Shore fishing for junk", "FISHING.ADS#7", ""},
    {"SCENE_25", "Fishing", "Shore fishing for keepers", "FISHING.ADS#8", ""},
    {"SCENE_26", "Story", "Johnny returns to the island", "JOHNNY.ADS#1", ""},
    {"SCENE_27", "Story", "Johnnys first message", "JOHNNY.ADS#2", ""},
    {"SCENE_28", "Story", "Johnnys final message", "JOHNNY.ADS#3", ""},
    {"SCENE_29", "Common", "Johnny finds a message bottle", "JOHNNY.ADS#4", ""},
    {"SCENE_30", "Common", "Johnny throws a message bottle", "JOHNNY.ADS#5", ""},
    {"SCENE_31", "Story", "Johnny dreams at work", "JOHNNY.ADS#6", ""},
    {"SCENE_32", "Mermaid", "Johnny and Mary have dinner", "MARY.ADS#1", ""},
    {"SCENE_33", "Mermaid", "Johnny asks Mary for a date", "MARY.ADS#3", ""},
    {"SCENE_34", "Mermaid", "Johnny first sees Mary", "MARY.ADS#2", ""},
    {"SCENE_35", "Mermaid", "Johnny and Mary break up", "MARY.ADS#4", ""},
    {"SCENE_36", "Escape", "Johnny leaves the island", "MARY.ADS#5", ""},
    {"SCENE_37", "Rare and Unusual", "Johnny melts in the sun", "MISCGAG.ADS#1", ""},
    {"SCENE_38", "Swimming", "Shark attacks Johnny", "MISCGAG.ADS#2", ""},
    {"SCENE_39", "Technical", "Ambient stand at A southwest", "STAND.ADS#1", ""},
    {"SCENE_40", "Technical", "Ambient stand at A west", "STAND.ADS#2", ""},
    {"SCENE_41", "Technical", "Ambient stand at A northwest", "STAND.ADS#3", ""},
    {"SCENE_42", "Technical", "Ambient stand at B southwest", "STAND.ADS#4", ""},
    {"SCENE_43", "Technical", "Ambient stand at B south", "STAND.ADS#5", ""},
    {"SCENE_44", "Technical", "Ambient stand at B southeast", "STAND.ADS#6", ""},
    {"SCENE_45", "Technical", "Ambient stand at C northeast", "STAND.ADS#7", ""},
    {"SCENE_46", "Technical", "Ambient stand at C east", "STAND.ADS#8", ""},
    {"SCENE_47", "Technical", "Ambient stand at D northwest", "STAND.ADS#9", ""},
    {"SCENE_48", "Technical", "Ambient stand at D northeast", "STAND.ADS#10", ""},
    {"SCENE_49", "Technical", "Ambient stand at E northwest", "STAND.ADS#11", ""},
    {"SCENE_50", "Technical", "Ambient stand at F northeast", "STAND.ADS#12", ""},
    {"SCENE_51", "Common", "Telescope at position A", "STAND.ADS#15", ""},
    {"SCENE_52", "Common", "Telescope at position C", "STAND.ADS#16", ""},
    {"SCENE_53", "Escape", "Suzy finds Johnnys message", "SUZY.ADS#1", ""},
    {"SCENE_54", "Escape", "Johnny meets Suzy", "SUZY.ADS#2", ""},
    {"SCENE_55", "Visitors", "Unseen visitors pass the island", "VISITOR.ADS#1", ""},
    {"SCENE_56", "Visitors", "A tanker visits the island", "VISITOR.ADS#3", ""},
    {"SCENE_57", "Common", "Coconut falls from the palm tree", "VISITOR.ADS#4", ""},
    {"SCENE_58", "Common", "Coconut rolls around the island", "VISITOR.ADS#6", ""},
    {"SCENE_59", "Common", "Johnny chases a coconut", "VISITOR.ADS#7", ""},
    {"SCENE_60", "Visitors", "Johnny hits a plane with a coconut", "VISITOR.ADS#5", ""},
    {"SCENE_61", "Visitors", "Would-be rescuers leave Johnny", "WALKSTUF.ADS#1", ""},
    {"SCENE_62", "Common", "Johnny builds his raft", "WALKSTUF.ADS#2", ""},
    {"SCENE_63", "Common", "Johnny goes jogging", "WALKSTUF.ADS#3", ""},
};
#endif

static const jcengine_special_day_t SPECIAL_DAYS[] = {
    {"HALLOWEEN", "Halloween", 10, 29, 10, 31, 1},
    {"ST_PATRICK", "St. Patrick", 3, 15, 3, 17, 2},
    {"CHRISTMAS", "Christmas", 12, 23, 12, 25, 3},
    {"NEW_YEAR", "New Year", 12, 29, 1, 1, 4},
};

const char *jcengine_scene_title(const char *ads_name, uint16_t ads_tag)
{
#if CONFIG_JC_SCENE_NAMES
    if (ads_name == NULL) return NULL;
    for (size_t index = 0; index < sizeof(SCENE_NAMES) / sizeof(SCENE_NAMES[0]); ++index) {
        if (SCENE_NAMES[index].ads_tag == ads_tag &&
            strcmp(SCENE_NAMES[index].ads_name, ads_name) == 0) {
            return SCENE_NAMES[index].title;
        }
    }
#else
    (void)ads_name;
    (void)ads_tag;
#endif
    return NULL;
}

size_t jcengine_scene_menu_count(void)
{
#if CONFIG_JC_SCENE_NAMES
    return sizeof(SCENE_MENU) / sizeof(SCENE_MENU[0]);
#else
    return 0;
#endif
}

const jcengine_scene_menu_entry_t *jcengine_scene_menu_entry(size_t index)
{
#if CONFIG_JC_SCENE_NAMES
    return index < jcengine_scene_menu_count() ? &SCENE_MENU[index] : NULL;
#else
    (void)index;
    return NULL;
#endif
}

size_t jcengine_special_day_count(void)
{
    return sizeof(SPECIAL_DAYS) / sizeof(SPECIAL_DAYS[0]);
}

const jcengine_special_day_t *jcengine_special_day(size_t index)
{
    return index < jcengine_special_day_count() ? &SPECIAL_DAYS[index] : NULL;
}

const jcengine_special_day_t *jcengine_special_day_for_date(uint8_t month, uint8_t day)
{
    uint16_t value = (uint16_t)month * 100U + day;
    for (size_t index = 0; index < jcengine_special_day_count(); ++index) {
        const jcengine_special_day_t *item = &SPECIAL_DAYS[index];
        uint16_t start = (uint16_t)item->start_month * 100U + item->start_day;
        uint16_t end = (uint16_t)item->end_month * 100U + item->end_day;
        bool match = start <= end ? value >= start && value <= end
                                  : value >= start || value <= end;
        if (match) return item;
    }
    return NULL;
}
