; Johnny Castaway persistent settings
; This file is safe to edit while Johnny Castaway is closed.

[Settings]
currentDay=0
date=0
crtFilter=0
crtMode=off
smoothing=0
scalingMode=nearest
scenesInOrder=0
windowed=0
mute=0
stretch=0
monitor=1
fastCRTSharpness=2
showPerformance=0
dataDirectory=
